# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1575, 735)

        # Create the main widget
        self.mainwidget = QtWidgets.QWidget(parent=MainWindow)
        self.mainwidget.setObjectName("mainwidget")

        #Place the gerber folder line edit and button
        self.place_gerber_folder()
        # Place the bitmap save folder line edit and button
        self.place_bitmap_save_folder()

        #
        self.place_scroll_widget()

        self.groupBox = QtWidgets.QGroupBox(parent=self.mainwidget)
        self.groupBox.setGeometry(QtCore.QRect(690, 50, 771, 631))
        self.groupBox.setObjectName("groupBox")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.mainwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(120, 440, 75, 24))
        self.pushButton_3.setObjectName("pushButton_3")
        self.color_top = QtWidgets.QCheckBox(parent=self.mainwidget)
        self.color_top.setGeometry(QtCore.QRect(180, 140, 76, 20))
        self.color_top.setObjectName("color_top")
        MainWindow.setCentralWidget(self.mainwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1575, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(parent=self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(parent=self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        self.menuSettings = QtWidgets.QMenu(parent=self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtGui.QAction(parent=MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtGui.QAction(parent=MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionInput_Gerber = QtGui.QAction(parent=MainWindow)
        self.actionInput_Gerber.setObjectName("actionInput_Gerber")
        self.actionInput_Tiffs = QtGui.QAction(parent=MainWindow)
        self.actionInput_Tiffs.setObjectName("actionInput_Tiffs")
        self.actionUndo_Last_Action = QtGui.QAction(parent=MainWindow)
        self.actionUndo_Last_Action.setObjectName("actionUndo_Last_Action")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuEdit.addAction(self.actionUndo_Last_Action)
        self.menuSettings.addAction(self.actionInput_Gerber)
        self.menuSettings.addAction(self.actionInput_Tiffs)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        # Connect the buttons to the functions
        self.gerber_folder_button.clicked.connect(self.gerber_folder_button_clicked)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.gerber_folder_button.setText(_translate("MainWindow", "Gerber Folder"))
        self.bitmap_save_button.setText(_translate("MainWindow", "Bitmap Save Folder"))
        self.groupBox.setTitle(_translate("MainWindow", "Output"))
        self.pushButton_3.setText(_translate("MainWindow", "Recolor"))
        self.color_top.setText(_translate("MainWindow", "CheckBox"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.menuSettings.setTitle(_translate("MainWindow", "Settings"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionInput_Gerber.setText(_translate("MainWindow", "Input Gerber"))
        self.actionInput_Tiffs.setText(_translate("MainWindow", "Input Tiffs"))
        self.actionUndo_Last_Action.setText(_translate("MainWindow", "Undo Last Action"))


    def place_gerber_folder(self):
        # Place line edit for gerber folder
        self.gerber_folder_line_edit = QtWidgets.QLineEdit(parent=self.mainwidget)
        self.gerber_folder_line_edit.setEnabled(True)
        self.gerber_folder_line_edit.setGeometry(QtCore.QRect(10, 10, 531, 21))
        self.gerber_folder_line_edit.setObjectName("gerber_folder_line_edit")
        # Place the gerber folder button
        self.gerber_folder_button = QtWidgets.QPushButton(parent=self.mainwidget)
        self.gerber_folder_button.setGeometry(QtCore.QRect(550, 10, 111, 21))
        self.gerber_folder_button.setObjectName("gerber_folder_button")

    def place_bitmap_save_folder(self):
        # Place line edit for bitmap save folder
        self.bitmap_to_save_line_edit = QtWidgets.QLineEdit(parent=self.mainwidget)
        self.bitmap_to_save_line_edit.setGeometry(QtCore.QRect(690, 10, 551, 21))
        self.bitmap_to_save_line_edit.setObjectName("bitmap_to_save_line_edit")
        # Place the bitmap save button
        self.bitmap_save_button = QtWidgets.QPushButton(parent=self.mainwidget)
        self.bitmap_save_button.setGeometry(QtCore.QRect(1250, 10, 121, 21))
        self.bitmap_save_button.setObjectName("bitmap_save_button")

    def place_scroll_widget(self):
        # Place the scroll area
        self.scrollArea = QtWidgets.QScrollArea(parent=self.mainwidget)
        self.scrollArea.setGeometry(QtCore.QRect(510, 60, 141, 601))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")

        # Place the scroll area widget contents
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)

        self.layout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.scrollAreaWidgetContents.setLayout(self.layout)

        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 139, 599))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")

        for i in range(50):  # Adjust the range as needed
            checkbox = QtWidgets.QCheckBox(f"Checkbox {i + 1}")
            self.layout.addWidget(checkbox)

    def gerber_folder_button_clicked(self):
        # options |= QtWidgets.QFileDialog.DontUseNativeDialog
        self.folder_name = QtWidgets.QFileDialog.getExistingDirectory(self.mainwidget, "Select Folder")

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
